import pandas as pd

df = pd.read_csv(r"D:\FILE AND TASK\TA\data\itera_noise\Masjid At-tanwir Frequency\analysis_summary.csv")
print("=" * 80)
print("HASIL ANALISIS AUDIO AUDIOMOTH: MASJID AT-TANWIR FREQUENCY (18 SEPTEMBER 2026)")
print("=" * 80)

for folder, g in df.groupby("folder"):
    print(f"\n[ DIREKTORI: {folder} ]")
    print(f"Jumlah Berkas         : {len(g)} berkas WAV")
    print(f"Rentang Waktu Header  : {g['rec_time'].iloc[0]} s/d {g['rec_time'].iloc[-1]}")
    print(f"Rentang Nama Berkas   : {g['filename'].iloc[0]} s/d {g['filename'].iloc[-1]}")
    print(f"Durasi per Berkas     : {g['duration_sec'].min()} s (semua sama: {g['duration_sec'].nunique() == 1})")
    print(f"Sample Rate           : {g['framerate'].iloc[0]} Hz (Mono 16-bit PCM)")
    print(f"Gain Terbaca Hardware : {g['actual_gain'].unique().tolist()}")
    print(f"Baterai AudioMoth     : {g['battery_v'].min():.2f} V - {g['battery_v'].max():.2f} V")
    print(f"Suhu Operasi          : {g['temp_c'].min():.1f} °C - {g['temp_c'].max():.1f} °C")
    print(f"Filter Center Freq    : {g['trig_center_khz'].iloc[0]} kHz")
    print(f"Filter Window Length  : {g['trig_window'].iloc[0]} samples")
    print(f"Trigger Threshold     : {g['trig_threshold_pct'].iloc[0]}%")
    print(f"Min Trigger Duration  : {g['trig_min_dur_s'].iloc[0]} s")
    print(f"Rata-rata RMS Energi  : {g['rms'].mean():.5f} (Min: {g['rms'].min():.5f}, Max: {g['rms'].max():.5f})")
    print(f"Peak Amplitudo        : Rata-rata {g['peak'].mean():.4f} (Max: {g['peak'].max():.4f})")
    print(f"Clipping / Distorsi   : {g['clipping_samples'].sum()} sampel (Berkas kliping: {sum(g['clipping_samples'] > 0)} dari {len(g)})")

print("\n" + "=" * 80)
print("ANALISIS KESELURUHAN (GLOBAL OVERVIEW):")
print("=" * 80)
print(f"Total Berkas Keseluruhan : {len(df)} berkas WAV (60 Low, 60 Medium, 60 High)")
print(f"Total Durasi Perekaman   : {len(df) * 55 / 60:.1f} menit ({len(df) * 55 / 3600:.2f} jam audio)")
print(f"Total Jam Pemantauan     : Tepat 3 Jam (3 sesi x 60 menit)")
print("=" * 80)
